server:
  port: 8081
spring:
  datasource:
    username: root
    password: root

    #url: jdbc:mysql://localhost:3306/an?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/an?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: html
    prefix: classpath:/templates/views/
    suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/templates/,classpath:/static/
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.an.an_be.entity

logging:
  level:
    com:
      example:
        mapper : debug
